--##############
--## ALIASES ###
--##############

-- programs
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.
home = os.getenv("HOME")
terminal = "alacritty"
multiplexer = "tmux"
menu = "fuzzel"
explorer = "firefox"
fileManager = "thunar"
-- local timer = HOME .. "/.config/waybar/scripts/waybar_timer"
statusbar = "waybar"
snip = "grim"
chat = "discord --enable-features=UseOzonePlatform --ozone-platform=wayland"
alerts = "swaync"
sync = "syncthing"
py = "python"
view = "zathura"
editor = "nvim"
host = "default"
style = "first-light"
