# Mikasa 

# color           = "#b9d2dc"
spacing         = 1
padding         = 0
hide_ascii      = false
separator       = "󰶻"
key_color       = "#8c57ff"
separator_color = "#e24091"

[custom_ascii]
# path="jp2a --width=auto ~/wallpapers/vball.png --color-depth=24"
path= "~/.config/macchina/artwork/macchina-ascii-art.txt"
# path= "~/Downloads/ubuntu-ascii.txt"
# ascii 256-color mode codes
# replace ESC with ESC character
# in neovim this is <C-v>27 while in INSERT mode
# ESC[38;5;18m           : dark blue
# ESC[38;5;220m          : bright yellow
# ascii ANSI color codes (24bit color terminal)
# ESC[38;2;255;215;0m    : yellow
# ESC[38;2;6;36;128m     : blue

[palette]
type            = "Dark"
visible         = true
glyph           = "●"
spacing         = 3

[bar]
# glyph           = "● "

# symbol_open     =
# symbol_close    =
# hide_delimiters = false
visible         = false
# 
[box]
color           = "#b9d2dc"
title           = " system "
border          = "double"
visible         = false

[box.inner_margin]
x               = 2
y               = 1

[randomize]     
key_color       = false
separator_color = false

[keys] 
# color           = "#b9d2dc"
host            = "󰠦 host"
kernel          = " kernel"
battery         = "󰂑 battery"
os              = "󰣇 os"
de              = "de"
wm              = " wm"
distro          = "󰣇 distro"
terminal        = "󰽒 terminal"
# shell           = " shell"
shell           = " shell"
packages        = " packages"
uptime          = "󱎫 uptime"
memory          = " memory"
machine         = "󰪫 machine"
local_ip        = " Local IP"
backlight       = " brightness"
resolution      = "resolution"
cpu_load        = "cpu load"
cpu             = "cpu"
gpu             = "gpu"
disk_space      = " disk"
