--######################
--## STARTUP ACTIONS ###
--######################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- exec-once = $timer serve    # must occur before waybar is started

-- exec-once = clight        # backlight control, necessary on laptop

-- setup default (base) workspace
-- exec-once = [workspace 1 silent] $multiplexer

-- setup browsing space
-- exec-once = [workspace 2 silent] $explorer

-- setup notes workspace

-- setup media space
-- exec-once = [workspace 4 silent] $music

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("python $HOME/projects/university-setup-fuzzel/scripts/countdown.py")
    hl.exec_cmd("$HOME/.config/waybar/launch-waybar.sh")     
    hl.exec_cmd("$sync")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("$HOME/.config/rice/listeners.sh --startall")
    hl.exec_cmd("walker --gapplication-service &")
end)
