--######################
--## STARTUP ACTIONS ###
--######################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("~/.config/hypr/conf/scripts/hyprbg.sh; set_diff")
    hl.exec_cmd("$alerts")
    hl.exec_cmd("python ~/projects/university-setup-fuzzel/scripts/countdown.py")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("$HOME/.config/waybar/launch-waybar.sh")
    hl.exec_cmd("sleep 2 && cd $HOME && source ~/projects/sunpaper/.venv/bin/activate && TZ='Australia/Sydney' ~/projects/sunpaper/sunpaper.py")
    hl.exec_cmd("$HOME/.config/rice/listeners.sh --startall")
    hl.exec_cmd("walker --gapplication-service &")
    -- odysseus background process
    hl.exec_cmd("source $HOME/applications/odysseus/.venv/bin/activate && cd $HOME/applications/odysseus && python -m uvicorn app:app --host 127.0.0.1 --port 7000")
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("~/.config/hypr/scripts/hyprland-lidstatus/lidstatus.sh check")
    hl.exec_cmd("hyprpaper")
end)

