--######################
--## STARTUP ACTIONS ###
--######################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("~/.config/hypr/conf/scripts/hyprbg.sh; set_diff")
    hl.exec_cmd("$alerts")
    hl.exec_cmd("python ~/projects/university-setup-fuzzel/scripts/countdown.py")
    hl.exec_cmd(statusbar .. " -s ~/.config/waybar/" .. style .. "/style.css")
    hl.exec_cmd("fcitx5")
    hl.exec_cmd("sleep 2 && cd $HOME && source ~/projects/sunpaper/.venv/bin/activate && TZ='Australia/Sydney' ~/projects/sunpaper/sunpaper.py")
    hl.exec_cmd(terminal)
end)

hl.on("config.reloaded", function()
    hl.exec_cmd("~/.config/hypr/scripts/hyprland-lidstatus/lidstatus.sh check")
    hl.exec_cmd("killall -SIGUSR2 " .. statusbar)
    hl.exec_cmd(statusbar .. " -s ~/.config/waybar/" .. host .. "-style.css")
end)

