--####################
--## BINDS DEFAULT ###
--####################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

mainMod = "SUPER" -- Sets "Windows" key as main modifier
hyprMod = "CTRL+ALT+SHIFT+SUPER" -- Create HYPR modifier for non application specific commands. 
-- Basic Binds provided by hyprland example config
hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exit())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(menu))
hl.bind(mainMod .. " + SHIFT + V", hl.dsp.window.pseudo())
-- bind = mainMod, N, 
-- bind = mainMod, P,
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.layout("togglesplit"))
-- Custom Application Binds
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd(explorer))
-- Utility Binds
hl.bind(mainMod .. " + SHIFT + R", hl.dsp.exec_cmd("hyprctl reload"))
-- hl.bind(mainMod .. " + ALT + W", hl.dsp.exec_cmd(statusbar .. " -s ~/.config/waybar/themes/" .. style .. "/setup/style.css"))
hl.bind(mainMod .. " + ALT + W", hl.dsp.exec_cmd("~/.config/waybar/launch-waybar.sh"))
hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("killall -SIGUSR2 " .. statusbar))
hl.bind(mainMod .. " + CTRL + W", hl.dsp.exec_cmd("~/.config/rice/scripts/wallpaper.sh"))
-- hl.bind(mainMod .. " + SHIFT + T", hl.dsp.exec_cmd("~/.config/waybar/themeselect.sh"))
hl.bind(mainMod .. " + CTRL + T", hl.dsp.exec_cmd("~/.config/rice/themes/themeselector.sh"))
-- Move focus with mainMod + vim motion keys
hl.bind(mainMod .. " + H", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + L", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + K", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + J", hl.dsp.focus({ direction = "down" }))
-- swap window location with mainMod + ALT + vim keys
hl.bind(mainMod .. " + ALT + H", hl.dsp.window.swap({ direction = "l" }))
hl.bind(mainMod .. " + ALT + L", hl.dsp.window.swap({ direction = "r" }))
hl.bind(mainMod .. " + ALT + K", hl.dsp.window.swap({ direction = "u" }))
hl.bind(mainMod .. " + ALT + J", hl.dsp.window.swap({ direction = "d" }))
-----------------------------------
-- DWINDLE LAYOUT SPECIFIC BINDS --
-----------------------------------
hl.bind(mainMod .. " + ALT + S", hl.dsp.layout("swapsplit"))
--###################

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 9 do
  hl.bind(mainMod .. " + " .. i, hl.dsp.focus({workspace = i}))
  hl.bind(mainMod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end
hl.bind(mainMod .. " + CTRL + K ", hl.dsp.focus({workspace = "k"}) )
-- 0 binds to workspace 10 not workspace 0 so can't be in for loop above
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))
-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + S", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
-- bind = mainMod, mouse_down, workspace, e+1
-- bind = mainMod, mouse_up, workspace, e-1

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl s 10%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl s 10%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

-- Submap for reszing active window using keyboard only
-- Create keybind to enter submap
hl.bind("ALT + R", hl.dsp.submap("resize"))
-- will start submap named resize
hl.define_submap("resize", function()
    -- repeatable keybinds for resizing active window
    hl.bind("right", hl.dsp.window.resize({ x = 10, y = 0, relative = true }), { repeating = true })
    hl.bind("left", hl.dsp.window.resize({ x = -10, y = 0, relative = true }), { repeating = true })
    hl.bind("up", hl.dsp.window.resize({ x = 0, y = -10, relative = true }), { repeating = true })
    hl.bind("down", hl.dsp.window.resize({ x = 0, y = 10, relative = true }), { repeating = true })
    -- use reset to go back to the global submap
    hl.bind("escape", hl.dsp.submap("reset"))
    -- will reset the submap, which will return to the global submap
end)

-- hyprpicker
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("hyprpicker | wl-copy"))
-- screenshot bindings
-- copy screenshot to clipboard, do not save
hl.bind(mainMod .. " + SHIFT + P", hl.dsp.exec_cmd("slurp | grim -g - - | wl-copy"))
-- copy screenshot to screenshots folder
hl.bind("Print", hl.dsp.exec_cmd("slurp | grim -g - ${HOME}/Pictures/Screenshots/$(date \"+%Y%m%d_%Hh%Mm%Ss_grim.png\")"))

--## Requires university-setup-fuzzel in the ~/projects directory
-- open course selection dialog
hl.bind(hyprMod .. " + S", hl.dsp.exec_cmd("source ~/projects/university-setup-fuzzel/.venv/bin/activate && TZ='Australia/NSW' python ~/projects/university-setup-fuzzel/scripts/fuzzel-courses.py"))

-- open currently compiled notes document
hl.bind(hyprMod .. " + O", hl.dsp.exec_cmd("source ~/.bashrc && " .. view .. " ~/notebook/current-course/master.pdf"))

-- open current course directory in terminal
hl.bind(hyprMod .. " + Q", hl.dsp.exec_cmd("source ~/.bashrc && " .. terminal .. " --working-directory ~/notebook/current-course"))

-- list all tutorial responses for current course, selecting one should open it in nvim -- DONE 
hl.bind(hyprMod .. " + T", hl.dsp.exec_cmd("source ~/projects/university-setup-fuzzel/.venv/bin/activate && TZ='Australia/NSW' python ~/projects/university-setup-fuzzel/scripts/fuzzel-tutorials.py"))

-- compile notes pdf (through selection dialogue) should compile and then open in viewer
hl.bind(hyprMod .. " + V", hl.dsp.exec_cmd("source ~/projects/university-setup-fuzzel/.venv/bin/activate && TZ='Australia/NSW' python ~/projects/university-setup-fuzzel/scripts/fuzzel-lectures-view.py"))

-- list all lecture notes for current course, selecting one should open it in nvim -- DONE 
hl.bind(hyprMod .. " + L", hl.dsp.exec_cmd("source ~/projects/university-setup-fuzzel/.venv/bin/activate && TZ='Australia/NSW' python ~/projects/university-setup-fuzzel/scripts/fuzzel-lectures.py"))

-- create a new lecture note
hl.bind(hyprMod .. " + N", hl.dsp.exec_cmd("source ~/projects/university-setup-fuzzel/.venv/bin/activate && python ~/projects/university-setup-fuzzel/scripts/create-lecture.py"))

-- create a new appendix
hl.bind(hyprMod .. " + A", hl.dsp.exec_cmd("source ~/projects/university-setup-fuzzel/.venv/bin/activate && python ~/projects/university-setup-fuzzel/scripts/create-appendix.py"))

hl.bind(hyprMod .. " + E", hl.dsp.exec_cmd("source ~/projects/university-setup-fuzzel/.venv/bin/activate && TZ='Australia/NSW' && " .. terminal .. " -e nvim ~/notebook/current-course"))

hl.bind(hyprMod .. " + Z", hl.dsp.exec_cmd("source ~/projects/university-setup-fuzzel/.venv/bin/activate && cd ~/notebook/current-course/pdf && python ~/projects/university-setup-fuzzel/scripts/fuzzel-zathura-view.py"))
--## Exercises sheets
-- compile exercises pdf 
-- bind = hyprMod E, exec, python ~/projects/university-setup-fuzzel/scripts/
-- view currently compiled pdf

--## ANKI bind
hl.bind(hyprMod .. " + R", hl.dsp.exec_cmd("~/.config/hypr/conf/scripts/anki-record/voice-record.sh record"))

