--#########################################
--## DESKTOP ONLY BINDS (MASTER LAYOUT) ###
--#########################################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind(mainMod .. " + mouse_down", hl.dsp.layout("rollprev"))
hl.bind(mainMod .. " + mouse_up", hl.dsp.layout("rollnext"))
hl.bind(mainMod .. " + A", hl.dsp.layout("addmaster"))
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.layout("removemaster"))

-- try grouped windows for nvim/zathura in master mode
-- bind = $hyprMod, A, exec, $terminal -D $HOME/notebook/current-course nvim master.tex
-- bind = $hyprMod, A, togglegroup
-- bind = $hyprMod, A, exec, $view $HOME/notebook/current-course/master.pdf
