--########################
--## LAPTOP ONLY BINDS ###
--########################
require("lua.binds.default")
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.bind(mainMod .. " + code:21", hl.dsp.exec_cmd("~/.config/hypr/conf/scripts/brightness.sh plus"))

hl.bind(mainMod .. " + MINUS", hl.dsp.exec_cmd("~/.config/hypr/conf/scripts/brightness.sh minus"))
-- modified status bar
-- TODO: manual review — 'unbind = $mainMod ALT, W'. In Lua, capture the result of hl.bind(...) and call :remove(). See hl.meta.lua.

-- bind = $hyprMod, W, exec, source ~/projects/sunpaper/.venv/bin/activate && python ~/projects/sunpaper/sunpaper.py  

--## hyprland-lidstatus binds for screen control

--bindl = , switch:on:Lid Switch, exec, ~/.config/hypr/conf/scripts/hyprland-lidstatus/lidstatus.sh close
--bindl = , switch:off:Lid Switch, exec, ~/.config/hypr/conf/scripts/hyprland-lidstatus/lidstatus.sh open

