--############################
--## DESKTOP WINDOW LAYOUT ###
--############################
--
-- should be sourced when using desktop computer with ultrawide monitor
--
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        layout = "master",
    },
    master = {
        new_status = "slave",
        orientation = "center", --default main window in center
        drop_at_cursor = true,
        mfact = 0.5,
        slave_count_for_center_master = 0,
        allow_small_split = true,
        center_master_slaves_on_right = false,
    },
})

