--####################
--## LAPTOP LAYOUT ###
--####################
--
--
--
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.config({
    general = {
        layout = "dwindle",
    },
    -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
    dwindle = {
        preserve_split = true,
        smart_split = false,
    },
})

