##########################
### WORKSPACE DEFAULTS ###
##########################

## $m3 = HDMI-1
### UNCOMMENT ON LAPTOP 
workspace = 1,monitor:eDP-1,rounding:true,decorate:true,gapsin:1,gapsout:3,persistent:true,default:true
workspace = 2,monitor:eDP-1,rounding:true,decorate:true,gapsin:1,gapsout:3,persistent:true
workspace = 3,monitor:eDP-1,rounding:true,decorate:true,gapsin:1,gapsout:3,persistent:true
workspace = 4,monitor:desc:Samsung Electric Company C49J89x H4ZN300228,rounding:true,decorate:true,gapsin:1,gapsout:2,default:true,persistent:true
workspace = 5,monitor:desc:Samsung Electric Company C49J89x H4ZN300228,rounding:true,decorate:true,gapsin:1,gapsout:2,persistent:true
workspace = 6,monitor:desc:Samsung Electric Company C49J89x H4ZN300228,rounding:true,decorate:true,gapsin:1,gapsout:2,persistent:true
workspace = 7,monitor:desc:Ancor Communications Inc ROG PG279Q HBLMQS061448,rounding:true,decorate:true,gapsin:1,gapsout:1,default:true,persistent:true
workspace = 8,monitor:desc:Ancor Communications Inc ROG PG279Q HBLMQS061448,rounding:true,decorate:true,gapsin:1,gapsout:1,persistent:true
### WORKSPACE RULES ###
