--##############################
--## DESKTOP WORKSPACE RULES ###
--##############################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local m0 = "eDP-1"
local m1 = "DP-1"
local m2 = "DP-2"
--# $m3 = HDMI-1
--## DESKTOP WORKSPACES
hl.workspace_rule({
    workspace = "1",
    monitor = "DP-1",
    rounding = true,
    decorate = true,
    gaps_in = 1,
    gaps_out = 4,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "DP-1",
    rounding = true,
    decorate = true,
    gaps_in = 1,
    gaps_out = 4,
})

hl.workspace_rule({
    workspace = "3",
    monitor = "DP-1",
    rounding = true,
    decorate = true,
    gaps_in = 1,
    gaps_out = 4,
})

hl.workspace_rule({
    workspace = "4",
    monitor = "DP-1",
    rounding = true,
    decorate = true,
    gaps_in = 1,
    gaps_out = 4,
})

hl.workspace_rule({
    workspace = "5",
    monitor = "DP-1",
    rounding = true,
    decorate = true,
    gaps_in = 1,
    gaps_out = 4,
})

hl.workspace_rule({
    workspace = "6",
    monitor = "DP-2",
    rounding = true,
    decorate = true,
    gaps_in = 1,
    gaps_out = 4,
})

hl.workspace_rule({
    workspace = "7",
    monitor = "DP-2",
    rounding = true,
    decorate = true,
    gaps_in = 1,
    gaps_out = 4,
})

hl.workspace_rule({
    workspace = "8",
    monitor = "DP-2",
    rounding = true,
    decorate = true,
    gaps_in = 1,
    gaps_out = 4,
})

hl.workspace_rule({
    workspace = "9",
    monitor = "DP-2",
    rounding = true,
    decorate = true,
    gaps_in = 1,
    gaps_out = 4,
})

hl.workspace_rule({
    workspace = "10",
    monitor = "DP-2",
    rounding = true,
    decorate = true,
    gaps_in = 1,
    gaps_out = 4,
})

--## UNCOMMENT ON LAPTOP 
-- workspace = 1,monitor:eDP-1,rounding:true,decorate:true,gapsin:1,gapsout:3
-- workspace = 2,monitor:eDP-1,rounding:true,decorate:true,gapsin:1,gapsout:3
-- workspace = 3,monitor:eDP-1,rounding:true,decorate:true,gapsin:1,gapsout:3
-- workspace = 4,monitor:eDP-1,rounding:true,decorate:true,gapsin:1,gapsout:3
-- workspace = 5,monitor:eDP-1,rounding:true,decorate:true,gapsin:1,gapsout:3

--## WORKSPACE RULES ###

-- ensure base 5 workspaces exist even when empty
hl.workspace_rule({
    workspace = "r[1]",
    ["on-created-empty"] = "foot",
})

hl.workspace_rule({
    workspace = "r[2]",
    ["on-created-empty"] = "firefox",
})

--workspace = r[1-5] m[0], persistent:true
-- window positioning on ultrawide monitors
hl.workspace_rule({
    workspace = "r[1-5] w[t1] m[0]",
    gaps_out = "4 960",
})

--workspace = r[1-5] w[t2] m[0], gapsout:4 480

hl.workspace_rule({
    workspace = "m[1]",
    layoutopt = "orientation:left",
})

