--################################
--## LAPTOP WORKSPACE DEFAULTS ###
--################################

--# $m3 = HDMI-1
--## UNCOMMENT ON LAPTOP 
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    decorate = true,
    gaps_in = 1,
    gaps_out = 3,
    persistent = true,
    default = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1",
    decorate = true,
    gaps_in = 1,
    gaps_out = 3,
    persistent = true,
})

hl.workspace_rule({
    workspace = "3",
    monitor = "eDP-1",
    decorate = true,
    gaps_in = 1,
    gaps_out = 3,
    persistent = true,
})

-- workspace = 4,monitor:desc:Samsung Electric Company C49J89x H4ZN300228,rounding:true,decorate:true,gapsin:1,gapsout:2,default:true,persistent:true
-- workspace = 5,monitor:desc:Samsung Electric Company C49J89x H4ZN300228,rounding:true,decorate:true,gapsin:1,gapsout:2,persistent:true
-- workspace = 6,monitor:desc:Samsung Electric Company C49J89x H4ZN300228,rounding:true,decorate:true,gapsin:1,gapsout:2,persistent:true

hl.workspace_rule({
    workspace = "4",
    monitor = "desc:Ancor Communications Inc ASUS PB287Q 0x00015C9F",
    decorate = true,
    gaps_in = 1,
    gaps_out = 2,
    default = true,
    persistent = true,
})

hl.workspace_rule({
    workspace = "5",
    monitor = "desc:Ancor Communications Inc ASUS PB287Q 0x00015C9F",
    decorate = true,
    gaps_in = 1,
    gaps_out = 2,
    persistent = true,
})

hl.workspace_rule({
    workspace = "6",
    monitor = "desc:Ancor Communications Inc ASUS PB287Q 0x00015C9F",
    decorate = true,
    gaps_in = 1,
    gaps_out = 2,
    persistent = true,
})

hl.workspace_rule({
    workspace = "7",
    monitor = "desc:Ancor Communications Inc ROG PG279Q HBLMQS061448",
    decorate = true,
    gaps_in = 1,
    gaps_out = 1,
    default = true,
    persistent = true,
})

hl.workspace_rule({
    workspace = "8",
    monitor = "desc:Ancor Communications Inc ROG PG279Q HBLMQS061448",
    decorate = true,
    gaps_in = 1,
    gaps_out = 1,
    persistent = true,
})

--## WORKSPACE RULES ###
