--##############
--## WINDOWS ###
--##############

-- Ignore maximize requests from apps. You'll probably like this.
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "prevent-maximize",
    match = {
        class = ".*",
    },
    suppress_event = "maximize",
})

-- Fix some dragging issues with XWayland
hl.window_rule({
    name = "xwayland-drag-fix",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
})

hl.window_rule({
    match = {
        workspace = 5,
        initial_class = "^(discord)$",
    },
})

-- force youtube picture in picture to be both floating and pinned when launched
hl.window_rule({
    match = {
        float = true,
        title = "^(Picture-in-Picture)$",
    },
})

hl.window_rule({
    match = {
        pin = true,
        title = "^(Picture-in-Picture)$",
    },
})

--## USER WINDOW RULES 
-- MUPDF opens with width ~= a4 paper width

hl.window_rule({
    match = {
        class = "(MuPDF)",
    },
    no_initial_focus = true,
    float = false,
    max_size = "734 2560",
})

hl.window_rule({
    match = {
        float = true,
        title = "^(MuPDF)",
    },
})

--##############
-- windowrule = maxsize 1920 1080, class:.*

hl.window_rule({
    match = {
        float = true,
        class = "^(matplotlib)",
    },
})

--##############
--## J-LINK Tools 
hl.window_rule({
    match = {
        initial_class = "(JLink)(.*)(Exe)",
    },
    tag = "+jlink",
})

hl.window_rule({
    match = {
        tag = "jlink",
    },
    center = true,
    size = "330 228",
})

--##############
--## KICAD 
hl.window_rule({
    match = {
        initial_class = "(KiCad)",
        initial_title = "negative:kicad",
    },
    tag = "+kicad",
})

-- windowrule = persistentsize, tag:kicad  
hl.window_rule({
    match = {
        initial_class = "(KiCad)",
        initial_title = "negative:kicad",
    },
    size = "800 600",
    float = true,
})

hl.window_rule({
    match = {
        tag = "kicad",
    },
    move = "onscreen cursor -50% -50%",
    float = true,
})

hl.window_rule({
    name = "float-python3-charts",
    match = {
        class = "python3",
        title = "Figure \\d*",
    },
    float = true,
})

--# Keep focus on gpick application
hl.window_rule({
    match = {
        class = "gpick",
        title = "Gpick",
    },
    stay_focused = true,
})


