--##############
--## WINDOWS ###
--##############
--## Laptop Specific

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    name = "float-python3-charts",
    match = {
        class = "python3",
        title = "Figure \\d*",
    },
    float = true,
})

--# Keep focus on gpick application
hl.window_rule({
    match = {
        class = "gpick",
        title = "Gpick",
    },
    stay_focused = true,
})

--#### KICAD 
