
###############
### WINDOWS ###
###############


# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = prevent-maximize
  match:class = .*
  suppress_event = maximize
}
# Fix some dragging issues with XWayland
windowrule {
  name = xwayland-drag-fix
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false
}


windowrule = match:workspace 5,match:initial_class ^(discord)$

# force youtube picture in picture to be both floating and pinned when launched
windowrule = match:float true, match:title ^(Picture-in-Picture)$
windowrule = match:pin true, match:title ^(Picture-in-Picture)$ 
### USER WINDOW RULES 
# MUPDF opens with width ~= a4 paper width

windowrule = no_initial_focus true, match:class (MuPDF), tile on, max_size 734 2560

windowrule = match:float true, match:title ^(MuPDF)
###############
# windowrule = maxsize 1920 1080, class:.*

windowrule = match:float true, match:class ^(matplotlib)

###############
### J-LINK Tools 
windowrule = tag +jlink, match:initial_class (JLink)(.*)(Exe)
windowrule = center true, match:tag jlink
windowrule = size 330 228, match:tag jlink

###############
### KICAD 
windowrule = tag +kicad, match:initial_class (KiCad), match:initial_title negative:kicad
# windowrule = persistentsize, tag:kicad  
windowrule = size 800 600, match:initial_class (KiCad),match:initial_title negative:kicad, float true
windowrule = move onscreen cursor -50% -50%, match:tag kicad, float true

