###############
### WINDOWS ###
###############
### Laptop Specific


windowrule {
  name=float-python3-charts
  match:class = python3
  match:title = Figure \d*
  float = true
}

## Keep focus on gpick application
windowrule = stay_focused on, match:class gpick, match:title Gpick


##### KICAD 
