--   _   _                  _                 _ 
--  | | | |                | |               | |
--  | |_| |_   _ _ __  _ __| | __ _ _ __   __| |
--  |  _  | | | | '_ \| '__| |/ _` | '_ \ / _` |
--  | | | | |_| | |_) | |  | | (_| | | | | (_| |
--  \_| |_/\__, | .__/|_|  |_|\__,_|_| |_|\__,_|
--          __/ | |                             
--         |___/|_|                             

-- =============================================
-- Monitor
-- =============================================
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/conf/monitors/laptop.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.monitors.laptop")
-- Source: ~/.config/hypr/conf/monitors/default.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.monitors.default")
-- =============================================
-- Source environment variables
-- =============================================
-- Source: ~/.config/hypr/conf/environments/default.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.environments.default")

-- =============================================
-- Source aliases file
-- =============================================
-- Source: ~/.config/hypr/conf/aliases/default.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.aliases.default")
-- Source: ~/.config/hypr/conf/aliases/laptop.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.aliases.laptop")

-- =============================================
-- Source miscellaneous options
-- =============================================
-- Source: ~/.config/hypr/conf/miscellaneous/laptop.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.miscellaneous.laptop")

-- =============================================
-- Source layout options
-- =============================================
-- Source: ~/.config/hypr/conf/layout/laptop.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.layout.laptop")

-- =============================================
-- Source windowrule options
-- =============================================
-- Source: ~/.config/hypr/conf/windows/default.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.windows.default")
-- Source: ~/.config/hypr/conf/windows/laptop.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.windows.laptop")

-- =============================================
-- Source input settings
-- =============================================
-- Source: ~/.config/hypr/conf/input/laptop.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.inputs.laptop")

-- =============================================
-- Source keybinds
-- =============================================
-- Source: ~/.config/hypr/conf/binds/default.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.binds.default")
-- Source: ~/.config/hypr/conf/binds/laptop.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.binds.laptop")

-- =============================================
-- Source workspace options
-- =============================================
-- Source: ~/.config/hypr/conf/workspaces/laptop.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.workspaces.laptop")

-- =============================================
-- Source autostart programs
-- =============================================
-- Source: ~/.config/hypr/conf/start/laptop.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lua.start.laptop")
