# Matugen Generated Theme for Tuxedo todo app

name = Matugen

bg = {{colors.background.default.hex}}
# panel = {{colors.background.default.hex | lighten: 10.0 }}
panel = {{colors.surface.default.hex}}
border = {{colors.outline.default.hex}}

fg = {{colors.primary.default.hex}}
dim = {{colors.primary_fixed_dim.default.hex}}
accent = {{colors.on_error.default.hex}}

cursor = {{colors.on_background.default.hex}}
selection = {{colors.on_primary.default.hex}}
statusbar = {{colors.secondary_container.default.hex}}
status_fg = {{colors.secondary_fixed_dim.default.hex}}

mode_fg = {{colors.on_tertiary.default.hex}}
mode_bg = {{colors.tertiary.default.hex}}

pri_a = {{colors.error.default.hex}}
pri_b = {{colors.tertiary.default.hex}}
pri_c = {{colors.tertiary.default.hex | auto_lightness: 10}}
pri_d = {{colors.tertiary.default.hex | auto_lightness: 20}}
pri_other = {{colors.surface_container_lowest.default.hex}}

project = {{colors.secondary.default.hex}}
context = {{colors.tertiary.default.hex}}
due = {{colors.error.default.hex}}
overdue = {{colors.error.default.hex}}
today = {{colors.error.default.hex | auto_lightness: 5}}
done = {{colors.surface_dim.default.hex}}
selected = {{colors.on_surface.default.hex}}
matched = {{colors.on_surface_variant.default.hex}}
