################
### MONITORS ###
################

### Transform list:
#   0 -> normal (no transforms)
#   1 -> 90 degrees
#   2 -> 180 degrees
#   3 -> 270 degrees
#   4 -> flipped
#   5 -> flipped + 90 degrees
#   6 -> flipped + 180 degrees
#   7 -> flipped + 270 degrees
# See https://wiki.hyprland.org/Configuring/Monitors/
# Inbuilt Display: (Laptop Only)
# 2880x1920 FW13 Display
monitorv2 {
  output = eDP-1
  mode = 2880x1920@120.0
  position = 0x0
  scale = 1.875000
}
# Default external ultrawide
#Samsung Electric Company C49J89x H4ZN300228
# monitor=desc:Samsung Electric Company C49J89x H4ZN300228, preferred, -480x-1080, auto
#monitor=desc:Ancor Communications Inc ASUS PB287Q 0x00015C9F, preferred, -2560x0, 1.50 
# 3840x2160 ASUS PB287Q
monitorv2 {
  output = desc:Ancor Communications Inc ASUS PB287Q 0x00015C9F
  mode = preferred
  position = -2880x0
  scale = 1.33
}
# 2560x1440 ASUS PG279Q
## left side monitor, positioned to left of main PB287Q, bottom inline, rotated 90degrees anticlockwise
# top left location calc: bottom right = bottom left of PB287Q, which is at 2160/1.25 = 1728, 1728 - 2560 = top left Y coord -832
monitorv2 {
  output = desc:Ancor Communications Inc ROG PG279Q HBLMQS061448
  mode = preferred
  position = -4320x-832
  scale = 1
  transform = 1
}
# monitor=desc:Ancor Communications Inc ROG PG279Q HBLMQS061448, preferred, -5280x-400, auto, transform, 1
# monitor=DP-2, preferred, -160x-2520, auto
# default external display settings
# monitor= , highres, auto, auto
# remove xwayland scaling?
xwayland {
force_zero_scaling = false
create_abstract_socket = true
}

