--##############################
--## DEFAULT GLOBAL SETTINGS ###
--##############################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.device({
  name = "wacom-bamboo-2fg-6x8-pen",
  output = "current",
  left_handed = true
})

