--############################
--## LAPTOP SPECIFIC INPUT ###
--############################

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})
hl.gesture({
    fingers = 4,
    direction = "up",
    action = "float",
    -- TODO: manual review — extra gesture field "float"
})
hl.gesture({
    fingers = 4,
    direction = "down",
    action = "float",
    -- TODO: manual review — extra gesture field "tile"
})
hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- float in range of [-1.0, 1.0], where 0 means no modification
        natural_scroll = false,
    },
    cursor = {
        no_hardware_cursors = true,
    },
    --########################
    --## TRACKPAD GESTURES ###
    --########################
    --## gesture = fingers, direction, action, options
})

