#############################
### LAPTOP SPECIFIC INPUT ###
#############################


input {
  kb_layout = us
  kb_variant = 
  kb_model = 
  kb_options =
  kb_rules = 
  
  follow_mouse = 1
  
  sensitivity = 0 # float in range of [-1.0, 1.0], where 0 means no modification
  natural_scroll = false
  
}
cursor {
  no_hardware_cursors = true
}

#########################
### TRACKPAD GESTURES ###
#########################
### gesture = fingers, direction, action, options

gestures {
  
  gesture = 3, horizontal, workspace      # change workspace with horizontal 3 finger swipe
  gesture = 4, up, float, float  
  gesture = 4, down, float, tile
}
